### ISSUE TITLE
why not  just click delete folder?

### ISSUE THREAD

**Issue by ghost** [Wscats/delete-node-modules#1]

**Comment by Wscats** [comment]
> _No description provided._

Because many times directly deleting the folder is not really completely deleted, you may also need to use the `npm cache clean` command to clear the cache. In some systems, if you need to use the graphical interface to delete, it may require a lot of consumption time. It may be unsuccessful (maybe because it is a large file, or the system does not have permissions, etc.)

**Comment by ghost** [comment]
Thank you.
